### ISSUE TITLE
1.3版本更新分数有问题

### ISSUE THREAD

**Issue by xxc0916** [A123asdo11/aircraft_war#1]
![image](https://cloud.githubusercontent.com/assets/19419772/19762998/d7eaf518-9c6e-11e6-8812-a6938ea2b01f.png)
这段会报错

**Comment by A123asdo11** [comment]
我这边没有报错，报的什么错，把错误日志贴出来，我看看

**Comment by xxc0916** [comment]
![image](https://cloud.githubusercontent.com/assets/19419772/19793320/bcdd3714-9cfe-11e6-9407-fb7967a71194.png)

**Comment by A123asdo11** [comment]
if (!preData) {}   是有判断的，这里如果严谨一点，判断是不是数组，应该就好了

**Comment by A123asdo11** [comment]
猜想你之前的浏览器是存过score，并且不是json串，这次修复了。 
preData = JSON.parse(preData);
        if (!(preData instanceof Array)){
              preData = [];    
            }
        preData.unshift(scoreData);

其实像这种浏览器测试，有时用的端口号可能是一样的，就会存在变量名一样，冲突的问题，统一给变量名加前缀，能解决这种问题

**Comment by A123asdo11** [comment]
猜想你之前的浏览器是存过score，并且不是json串，这次修复了。 
preData = JSON.parse(preData);
if (!(preData instanceof Array)){
preData = [];

}
preData.unshift(scoreData);

其实像这种浏览器测试，有时用的端口号可能是一样的，就会存在变量名一样，冲突的问题，统一给变量名加前缀，能解决这种问题
